<a href="https://colab.research.google.com/github/adljna/ProjectA-Group3-KematianAliKhamenei/blob/main/Data%20Integration/3_MergeArticle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Merge Article News**

Notebook ini menggabungkan beberapa file CSV menjadi satu file output.

## **(1) Konfigurasi**
Sesuaikan `csv_files` dan `output_file` sesuai kebutuhan.

In [ ]:
import pandas as pd
import os

In [ ]:
csv_files = [
    "analyzed_articles_detik.csv",
    "analyzed_articles_kompas.csv",
    "analyzed_articles_tribun.csv",
    "analyzed_articles_antara.csv",
    "analyzed_articles_cnn.csv"
]

output_file = "merged_articles.csv"   # nama file output
add_source_column = True              # Tambahkan kembali variabel ini agar kolom 'News' ditambahkan

## **(2) Load & Preview Setiap File**

In [ ]:
dfs = []
source_map = {
    "analyzed_articles_detik": "Detik",
    "analyzed_articles_kompas": "Kompas",
    "analyzed_articles_tribun": "Tribun",
    "analyzed_articles_antara": "Antara",
    "analyzed_articles_cnn": "CNN"
}

for filepath in csv_files:
    if not os.path.exists(filepath):
        print(f"[WARNING] File tidak ditemukan: {filepath} — dilewati.")
        continue

    df = pd.read_csv(filepath)

    if add_source_column:
        # Ambil nama file tanpa ekstensi
        filename_base = os.path.splitext(os.path.basename(filepath))[0]
        # Dapatkan nama sumber dari mapping
        source_label = source_map.get(filename_base, "Unknown Source")
        df.insert(0, "News", source_label)

    dfs.append(df)
    print(f"✅ {filepath:45s} → {len(df):,} baris, {df.shape[1]} kolom")

print(f"\nTotal file berhasil dimuat: {len(dfs)}")

✅ analyzed_articles_detik.csv                   → 100 baris, 12 kolom
✅ analyzed_articles_kompas.csv                  → 100 baris, 12 kolom
✅ analyzed_articles_tribun.csv                  → 100 baris, 12 kolom
✅ analyzed_articles_antara.csv                  → 100 baris, 12 kolom
✅ analyzed_articles_cnn.csv                     → 99 baris, 12 kolom

Total file berhasil dimuat: 5

## **(3) Merge Data**

In [ ]:
if not dfs:
    raise ValueError("Tidak ada file yang berhasil dimuat. Periksa path file.")

merged = pd.concat(dfs, ignore_index=True)

merged.to_csv(output_file, index=False)

print(f"✅ File berhasil disimpan: {output_file}")
print(f"   Total baris  : {len(merged):,}")
print(f"   Total kolom  : {merged.shape[1]}")

✅ File berhasil disimpan: merged_articles.csv
   Total baris  : 499
   Total kolom  : 12

In [ ]:
print("=== 5 Baris Pertama ===")
display(merged.head())

print("\n=== Info Kolom ===")
merged.info()

if add_source_column:
    print("\n=== Distribusi per Sumber (Kolom 'News') ===")
    display(merged["News"].value_counts().rename_axis("News").reset_index(name="jumlah_artikel"))

=== 5 Baris Pertama ===

,News,url,title,content,text_cleaned,tokens,tokens_no_stop,tokens_stemmed,text_final,polarity,subjectivity,sentiment_label
0,Detik,https://news.detik.com/berita/d-8392835/puan-b...,Puan Berduka Ali Khamenei Gugur Diserang AS-Is...,Ketua DPR RI Puan Maharani menyampaikan dukaci...,ketua dpr ri puan maharani menyampaikan dukaci...,"['ketua', 'dpr', 'ri', 'puan', 'maharani', 'me...","['ketua', 'dpr', 'ri', 'puan', 'maharani', 'du...","['ketua', 'dpr', 'ri', 'puan', 'maharani', 'du...",ketua dpr ri puan maharani dukacita masyarakat...,0.014035,0.185965,Netral
1,Detik,https://news.detik.com/internasional/d-8392814...,Trump Beri Sinyal Perang Lawan Iran Akan Selesai,Presiden Amerika Serikat (AS) Donald Trump men...,presiden amerika serikat as donald trump menga...,"['presiden', 'amerika', 'serikat', 'as', 'dona...","['presiden', 'amerika', 'serikat', 'as', 'dona...","['presiden', 'amerika', 'serikat', 'as', 'dona...",presiden amerika serikat as donald trump peran...,-0.033333,0.200000,Netral
2,Detik,https://www.detik.com/bali/berita/d-8392847/pe...,Peringatan Keras Iran ke Kapal Tanker yang Nek...,\n Ilyas Fa...,ilyas fadilah detikbali harga minyak dunia mel...,"['ilyas', 'fadilah', 'detikbali', 'harga', 'mi...","['ilyas', 'fadilah', 'detikbali', 'harga', 'mi...","['ilyas', 'fadilah', 'detikbali', 'harga', 'mi...",ilyas fadilah detikbali harga minyak dunia lon...,0.061053,0.470526,Positive
3,Detik,https://finance.detik.com/energi/d-8392622/ira...,Iran Beri Peringatan Keras Kapal Tanker yang M...,"Juru Bicara Kementerian Luar Negeri Iran, Esma...",juru bicara kementerian luar negeri iran esmai...,"['juru', 'bicara', 'kementerian', 'luar', 'neg...","['juru', 'bicara', 'kementerian', 'negeri', 'i...","['juru', 'bicara', 'menteri', 'negeri', 'iran'...",juru bicara menteri negeri iran esmail baghaei...,0.004545,0.414773,Netral
4,Detik,https://finance.detik.com/energi/d-8392622/ira...,Iran Beri Peringatan Keras Kapal Tanker yang M...,"Juru Bicara Kementerian Luar Negeri Iran, Esma...",juru bicara kementerian luar negeri iran esmai...,"['juru', 'bicara', 'kementerian', 'luar', 'neg...","['juru', 'bicara', 'kementerian', 'negeri', 'i...","['juru', 'bicara', 'menteri', 'negeri', 'iran'...",juru bicara menteri negeri iran esmail baghaei...,0.004545,0.414773,Netral

=== Info Kolom ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   News             499 non-null    object
 1   url              499 non-null    object
 2   title            495 non-null    object
 3   content          491 non-null    object
 4   text_cleaned     491 non-null    object
 5   tokens           499 non-null    object
 6   tokens_no_stop   499 non-null    object
 7   tokens_stemmed   499 non-null    object
 8   text_final       491 non-null    object
 9   polarity         499 non-null    float64
 10  subjectivity     490 non-null    float64
 11  sentiment_label  499 non-null    object
dtypes: float64(2), object(10)
memory usage: 46.9+ KB

=== Distribusi per Sumber (Kolom 'News') ===

     News  jumlah_artikel
0   Detik             100
1  Kompas             100
2  Tribun             100
3  Antara             100
4     CNN              99